DROP TABLE IF EXISTS FILME_CATEGORIA;
DROP TABLE IF EXISTS MENSALIDADE;
DROP TABLE IF EXISTS CATEGORIAS;
drop table if exists usuario_filme_lista;
DROP TABLE IF EXISTS ASSISTIDOS;
-- DROP TABLE IF EXISTS ASSINATURAS;
DROP TABLE IF EXISTS pedidos;
DROP TABLE IF EXISTS USUARIOS;

DROP TABLE IF EXISTS FILMES;

DROP TABLE IF EXISTS produtos;
