
INSERT INTO filmes (id_filme, sinopse, titulo, avaliacao, ano, faixa_etaria, duracao, direcao, elenco, roteiro, produtora, avatar)
values 
(1, 'Uma menina entra escondida no navio de um grande caçador de monstros marinhos. Juntos, eles iniciam uma jornada épica por águas desconhecidas.', 'A Fera do Mar', 3.9, 2022, 0, 115, 'Chris Williams (IX)', 'Karl Urban Jacob Holland (voz), Zaris-Angel Hator Maisie Brumble (voz), Dan Stevens (IV) Almirante Hornagold (voz), Doon Mackichan Rainha (voz), Helen Sadler Sra. Merino / Matrona (voz)', 'Chris Williams (IX), Nell Benjamin', 'Netflix', 'a_fera_do_mar.jpg'),
(2, 'Quando Nemo, um jovem peixe-palhaço é capturado inesperadamente, seu pai Marlin se vê obrigado a embarcar em uma emocionante aventura de resgate. No caminho ele conhece Dory, uma peixinha muito divertida que vai ajudá-lo a enfrentar tubarões, águas-vivas e muito mais.', 'Procurando Nemo', 4.2, 2003, 0, 100, 'Andrew Stanton, Lee Unkrich', 'Albert Brooks Marlin (Voz), Alexander Gould Nemo (Voz), Allison Janney Peach (Voz), Brad Garrett Bloat (Voz), Ellen DeGeneres Dory (Voz)', 'Andrew Stanton, Bob Peterson', 'Pixar', 'procurando_nemo.jpg'),
(3, 'Depois que a caverna da família Crood é destruída, o clã se vê obrigado a partir em busca de uma nova casa. Liderados por Grug, só não imaginavam que sair das cavernas ia render a maior aventura de suas vidas.', 'Os Croods', 3.7, 2013, 0, 98, 'Chris Sander (III), Kirk DeMicco', 'Ryan Reynolds Guy (voice), Catherine Keener Ugga, Chris Sanders (II) Belt, Clark Duke Thunk, Cloris Leachman Gran', 'Chris Sander (III), Kirk DeMicco, John Cleese', 'DreamWorks', 'os_croods.jpg'),
(4, 'Zootopia é uma cidade diferente de tudo o que você já viu. Formada por “bairros-habitat”, como a elegante Praça Sahara e a gelada Tundralândia, essa metrópole abriga uma grande diversidade de animais irreverentes sempre prontos para encarar uma nova e divertida aventura.Quando Judy Hopps chega em Zootopia, ela descobre que ser a primeira coelha da equipe da polícia, formada por animais grandes e fortes, não é nada fácil. Determinada a provar seu valor, ela embarca em uma aventura atrapalhada e bem humorada, ao lado do malandro raposo Nick Wilde para desvendar um grande mistério.', 'Zootopia: Essa Cidade é o Bicho', 4.2, 2016, 0, 108, 'Byron Howard, Rich Moore', "Bonnie Hunt Bonnie Hopps (voz), Idris Elba Chief Bogo (voz), J. K. Simmons Mayor Lionheart (voz), Shakira (I) Gazelle (voz), Tommy 'Tiny' Lister Finnick (voz)", 'Byron Howard, Jared BushJared Bush, Jennifer Lee, Jim Reardon, Josie Trinidad, Phil Johnston, Rich Moore', 'Disney', 'zootopia.jpg'),
(5, 'Crescer pode ser uma jornada turbulenta, e com Riley não é diferente. Ela é retirada de sua vida no meio-oeste americano quando seu pai arruma um novo emprego em São Francisco. Como todos nós, Riley é guiada pelas emoções – Alegria, Medo, Raiva, Nojinho e Tristeza. As emoções vivem no centro de controle dentro da mente de Riley, onde a ajudam com conselhos em sua vida cotidiana. Conforme Riley e suas emoções se esforçam para se adaptar à nova vida em São Francisco, começa uma agitação no centro de controle. Embora Alegria, a principal e mais importante emoção de Riley, tente se manter positiva, as emoções entram em conflito sobre qual a melhor maneira de viver em uma nova cidade, casa e escola.', 'Divertida Mente', 4.3, 2015, 0, 94, 'Pete Docter', 'Amy Poehler Alegria (voz), Bill Hader Medo (voz), Kaitlyn Dias Riley (voz), Lewis Black Raiva (voz), Mindy Kaling Nojinho (voz)', 'Josh Cooley, Meg LeFauve, Pete Docter, Ronnie del Carmen', 'Pixar', 'divertida_mente.jpg'),
(6, 'Moana Waialiki é uma corajosa jovem, filha do chefe de uma tribo na Oceania, vinda de uma longa linhagem de navegadores, que é seu maior hobbie e, também, trabalho. Querendo descobrir mais sobre seu passado e ajudar sua família, ela resolve partir em busca de seus ancestrais, habitantes de uma ilha mítica que ninguém sabe onde é. Com a ajuda do lendário semideus Maui, Moana começa sua jornada pelo mar aberto, onde vai enfrentar criaturas marinhas e descobrir antigas histórias do submundo', 'Moana: Um Mar de Aventuras', 4.1, 2016, 0, 113, 'John Musker Ron Clements', "Auli'i Cravalho Moana (voz), Dwayne Johnson Maui (voz), Alan Tudyk Heihei (voz), Jemaine Clement Tamatoa (voz), Nicole Scherzinger Sina (voz)", 'Aaron Kandell, Chris Williams (IX),Don Hall (II),Jared Bush, John Musker, Jordan Kandell, Pamela Ribon, Ron Clements', 'Disney', 'moana.jpg'),
(7, 'Um velhinho viúvo chamado Carl Fredricksen, com seus setenta e poucos anos de idade, passou a vida sonhando em explorar o planeta e viver plenamente a vida. Até que um plano mirabolante invade sua cabeça teimosa: fazer sua casa inteira levantar voo através de balões e transportá-la dos Estados Unidos a um lugar em meio às montanhas da Venezuela.', 'Up: Altas Aventuras', 4.1, 2009, 0, 96, 'Pete Docter', 'Christopher Plummer Charles Muntz (voz), Edward Asner Carl Fredricksen (voz), Jordan Nagai Russell (voz), Bob Bergen Voz Adicional (voz), Bob Peterson (III) Dug / Alpha (voz)', 'Bob Peterson (III), Pete Docter, Tom McCarthy (XXII)', 'Pixar', 'up_altas_aventuras.jpg'),
(8, 'O astro do susto, Sulley, e seu falante assistente, Mike, trabalham na Monstros S.A., a maior fábrica de processamento de gritos da cidade de Monstrópolis. A principal fonte de energia do mundo dos monstros provém da coleta dos gritos das crianças humanas. Os monstros acreditam que as crianças são tóxicas, e entram em Pânico quando uma menininha invade seu mundo. Sulley e Mike fazem de tudo para levar a garota de volta para casa, mas enfrentam desafios monstruosos e algumas situações hilárias em suas atrapalhadas aventuras.', 'Monstros S.A.', 4.1, 2001, 0, 92, 'Pete Docter', 'Billy Crystal Mike Wazowski, John Goodman James P. "Sulley" Sullivan, Ashley Edner Voz Adicional, Bill Farmer (I) Voz Adicional, Bob Bergen Voz Adicional', 'Andrew Stanton, Daniel Gerson, Jeff Pidgeon, Jill Culton, Pete Docter, Ralph Eggleston', 'Pixar', 'monstros_sa.jpg'),
(9, 'Paris. Remy é um rato que sonha se tornar um grande chef. Só que sua família é contra a idéia, além do fato de que, por ser um rato, ele sempre é expulso das cozinhas que visita. Um dia, enquanto estava nos esgotos, ele fica bem embaixo do famoso restaurante de seu herói culinário, Auguste Gusteau. Ele decide visitar a cozinha do lugar e lá conhece Linguini, um atrapalhado ajudante que não sabe cozinhar e precisa manter o emprego a qualquer custo. Remy e Linguini realizam uma parceria, em que Remy fica escondido sob o chapéu de Linguini e indica o que ele deve fazer ao cozinhar.', 'Ratatouille', 4.1, 2007, 0, 111, 'Brad Bird', 'Lou Romano Linguini, Patton Oswalt Remy, Andrea Boerries Vozes Adicionais, Brad Bird Ambrister Minion, Brad Garrett Gusteau, Brad Lewis Abusive Boyfriend (voz), Brian Dennehy Django, Ian Holm Skinner, Jack Bird Vozes Adicionais, Jake Steinfeld Git (Lab Rat), James Remar Larousse, Janeane Garofalo Colette, John Ratzenberger Mustafa', 'Brad Bird, Jan Pinkava, Jim Capobianco', 'Pixar', 'ratatouille.jpg'),
(10, 'Mufasa (James Earl Jones), o Rei Leão, e a rainha Sarabi (Madge Sinclair) apresentam ao reino o herdeiro do trono, Simba (Matthew Broderick). O recém-nascido recebe a bênção do sábio babuíno Rafiki (Robert Guillaume), mas ao crescer é envolvido nas artimanhas de seu tio Scar (Jeremy Irons), o invejoso e maquiavélico irmão de Mufasa, que planeja livrar-se do sobrinho e herdar o trono.', 'O Rei Leão', 4.1, 1994, 0, 89, 'Rob Minkoff Roger Allers', 'Ernie Sabella Pumbaa the Warthog, James Earl Jones King Mufasa, Jeremy Irons Scar, Matthew Broderick Adult Simba, Nathan Lane Timon the Meerkat', 'Andy Gaskill, Barry Johnson, Bob Tzudiker, Burny Mattinson, Chris Sanders (II), Ed Gombert, Francis Glebas, Gary Trousdale, Irene Mecchi, Jim Capobianco, Joe Ranft, Jonathan Roberts, Jorgen Klubien, Kevin Harkey, Larry Leker, Linda Woolverton, Lorna Cook, Mark Kausler, Miguel Tejada-Flores, Rick Maki, Thom Enriquez, Tom Sito', 'Disney', 'o_rei_leao.jpg'),
(11, 'Todo ano, os gananciosos gafanhotos exigem uma parte da colheita das formigas. Mas quando algo dá errado e a colheita é destruída, os gafanhotos ameaçam atacar e as formigas são forçadas a pedir ajuda a outros insetos para enfrentá-los numa batalha.', 'Vida de Inseto', 4.1, 1998, 0, 95, 'Andrew Stanton John Lasseter', 'Alex Rocco Thorny, Andrew Stanton Vozes Adicionais,Anthony Burch Vozes Adicionais, Ashley Tisdale Lead Blueberry Scout, Bill Farmer (I) Vozes Adicionais', 'Andrew Stanton, John Lasseter', 'Pixar', 'vida_de_inseto.jpg'),
(12, 'O aniversário de Andy está chegando e os brinquedos estão nervosos. Afinal de contas, eles temem que um novo brinquedo possa substituí-los. Liderados por Woody, um caubói que é também o brinquedo predileto de Andy, eles montam uma escuta que lhes permite saber dos presentes ganhos. Entre eles está Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Isto aos poucos gera ciúmes em Woody, que tenta fazer com que ele caia atrás da cama. Só que o plano dá errado e Buzz cai pela janela. É o início da aventura de Woody, que precisa resgatar Buzz também para limpar sua barra com os outros brinquedos.', 'Toy Story', 4.1, 1995, 0, 81, 'John Lasseter', 'Annie Potts Bo Peep, Don Rickles Mr. Potato Head, Jim Varney Slinky Dog, Tim Allen Buzz Lightyear, Tom Hanks Woody', 'Alec Sokolow, Andrew Stanton,  Joel Cohen (I), Joe Ranft, John Lasseter, Joss Whedon, Pete Docter', 'Pixar', 'toy_story.jpg'),
(13, 'Ariel é uma vibrante princesa sereia que anseia fazer parte do mundo dos humanos. Depois de corajosamente fazer um acordo com Úrsula, uma malvada feiticeira do mar, Ariel embarca em uma aventura sem igual. Mas o destino do reino de seu pai está em suas mãos. Com Linguado e Sebastião ao seu lado, Ariel precisará de toda a coragem e determinação para fazer a coisa certa nos dois mundos.', 'A Pequena Sereia', 4.1, 1989, 0, 82, ' John Musker Ron Clements', 'Jodi Benson Ariel, Anne Lockhart Vozes Adicionais, Ben Wright Grimsby, Buddy Hackett Scuttle, Charlie Adler Vozes Adicionais', 'Hans Christian Andersen, Howard Ashman,John Musker, Ron Clements,', 'Disney', 'a_pequena_sereia.jpg'),
(14, 'A destemida e otimista Anna sai em uma jornada épica, ao lado de Kristoff e sua leal rena Sven, para encontrar sua irmã Elsa, cujos poderes congelantes aprisionaram o reino de Arendelle em um inverno eterno. Encontrando condições de Everest, trolls místicos e um hilário boneco de neve chamado Olaf, Anna e Kristoff enfrentam obstáculos em uma corrida para salvar o reino.', 'Frozen: Uma Aventura Congelante', 4.1, 2014, 0, 102, 'Chris Buck Jennifer Lee (XXX)', 'Idina Menzel Elsa (voz), Jonathan Groff Kristoff (voz), Josh Gad Olaf (voz), Kristen Bell Anna (Voz), Santino Fontana Hans (voz)', 'Chris Buck, Hans Christian Andersen, Jennifer Lee (XXX), Shane Morris', 'Disney', 'frozen.jpg'),
(15, 'A Walt Disney Pictures apresenta "Enrolados", uma comédia de animação musical com muita ação sobre uma menina com mágicos cabelos dourados de mais de 21 metros de comprimento. Rapunzel, a princesa que foi raptada do castelo de seus pais quando bebê é mantida presa em uma torre e sonha com aventuras. Agora uma adolescente determinada e criativa, ela realiza uma fuga de arrepiar os cabelos com ajuda de um ousado bandido. Com o segredo de sua linhagem pesando na balança e seu captor em seu encalço, Rapunzel e seu amigo encontram aventura, emoção, humor e cabelos... muitos cabelos. Com música de Alan Menken, esta comédia reimaginada do clássico dos irmãos Grimm chega às telas dos cinemas em Disney Digital 3D™.', 'Enrolados', 4.1, 2010, 0, 100, ' Byron Howard, Nathan Greno', 'Elenco de Enrolados, Mandy Moore Rapunzel (Voz), Zachary Levi Príncipe Flynn (Voz), Brad Garrett Hook Hand Thug (Voz), Byron Howard Guard #2 / Thug #2 (Voz), David Cowgill Additional Voices', 'Dan Fogelman, Jacob Grimm, Wilhelm Grimm', 'Disney', 'enrolados.jpg'),
(16, 'Em um pântano distante vive Shrek (Mike Myers), um ogro solitário que vê, sem mais nem menos, sua vida ser invadida por uma série de personagens de contos de fada, como três ratos cegos, um grande e malvado lobo e ainda três porcos que não têm um lugar onde morar. Todos eles foram expulsos de seus lares pelo maligno Lorde Farquaad (John Lithgow). Determinado a recuperar a tranquilidade de antes, Shrek resolve encontrar Farquaad e com ele faz um acordo: todos os personagens poderão retornar aos seus lares se ele e seu amigo Burro (Eddie Murphy) resgatarem uma bela princesa (Cameron Diaz), que é prisioneira de um dragão. Porém, quando Shrek e o Burro enfim conseguem resgatar a princesa logo eles descobrem que seus problemas estão apenas começando.', 'Shrek', 4, 2001, 0, 90, ' Andrew Adamson Vicky Jenson', 'Cameron Diaz Princess Fiona, Eddie Murphy Donkey, Mike Myers Shrek, Andrew Adamson Duloc Mascot, Bobby Block Baby Bear', 'Joe Stillman, Roger S.H. Schulman, Ted Elliott, Terry RossioTerry Rossio, William Steig', 'DreamWorks', 'shrek.jpg'),
(17, 'Em plena Era Glacial, um grupo de animais, incluindo um tigre dentes-de-sabre, um mamute e algumas preguiças gigantes, encontra uma criança perdida. Juntos, eles decidem por procurar a família do menino, para que possam devolvê-lo.', 'A Era do Gelo', 4, 2002, 0, 81, 'Carlos Saldanha (I) Chris Wedge', 'Alan Tudyk Oscar/Dab the Dodo, Cedric the Entertainer Carl, Chris Wedge Dodo/Scrat, Denis Leary Diego, Denny Dillon Glyptodon (voice)', 'Doug Compton, Galen T. Chu, James Bresnahan, Jeff Siergey, Michael J. Wilson, Mike Thurmeier, Peter Ackerman, Xeth Feinberg', 'Fox Animation', 'a_era_do_gelo.jpg'),
(18, 'Joe Gardner é um professor de música de ensino fundamental desanimado por não conseguir alcançar seu sonho de tocar no lendário clube de jazz The Blue Note, em Nova York. Quando um acidente o transporta para fora do seu corpo, fazendo com que ele exista em outra realidade na forma de sua alma, ele se vê forçado a embarcar em uma aventura ao lado da alma de uma criança que ainda está aprendendo sobre si, para aprender o que é necessário para retomar sua vida.', 'Soul', 4, 2020, 0, 100, 'Kemp Powers Pete Docter', 'Ahmir-Khalib Thompson Curly (voz), Jamie Foxx Joe Gardner (voz), Phylicia Rashad Libba Gardner (voz), Tina Fey 22 (voz), Alice Braga Jerry (voz)', 'Kemp Powers, Pete Docter', 'Pixar', 'soul.jpg'),
(19, 'Quarenta anos da história dos Estados Unidos, vistos pelos olhos de rapaz com QI abaixo da média que, por obra do acaso, consegue participar de momentos cruciais, como a Guerra do Vietnã e Watergate.', 'Forrest Gump: O Contador de Histórias', 4.5, 1994, 14, 142, 'Robert Zemeckis', 'Tom Hanks , Aaron Izbicki , Aaron Michael , Afemo Omilami , Alexander Zemeckis', 'Eric Roth, Winston Groom', 'Paramount', 'forrest_gump.jpg'),
(20, 'Na Itália dos anos 40, Guido (Roberto Benigni) é levado para um campo de concentração nazista e tem que usar sua imaginação para fazer seu pequeno filho acreditar que estão participando de uma grande brincadeira, com o intuito de protegê-lo do terror e da violência que os cercam.', 'A Vida é Bela ', 4.5, 1997, 0, 116, 'Roberto Benigni', 'Giorgio Cantarini , Nicoletta Braschi , Roberto Benigni, Aaron Craig ,Alessandra Grassi', 'Roberto Benigni, Vincenzo Cerami', 'Miramax', 'a_vida_e_bela.jpg'),
(21, 'Filmado ao longo de 12 anos, “Boyhood - Da Infância à Juventude” conta a história de um casal de pais divorciados (Ethan Hawke e Patricia Arquette) que tenta criar seu filho Mason (Ellar Coltrane). A narrativa percorre a vida do menino durante um período de doze anos, da infância à juventude, e analisa sua relação com os pais conforme ele vai amadurecendo.', 'Boyhood: Da Infância à Juventude', 4.0, 2014, 14, 165, 'Richard Linklater', 'Ellar Coltrane, Ethan Hawke, Lorelei Linklater, Patricia Arquette, Andrea Chen', 'Richard Linklater', 'IFC Productions', 'boyhood.jpg'),
(22, 'Durante a Segunda Guerra Mundial, o alto comando do exército descobre que quatro irmãos Ryan estavam nas forças armadas e que três deles foram mortos. O Capitão John Miller (Tom Hanks) é designado para salvar o último soldado da família Ryan que ainda está vivo e retirá-lo do conflito. Porém, é preciso descobrir onde ele está, percorrendo diversas regiões do território em guerra. Durante a missão, Miller e seus soldados enfrentam inimigos e seus próprios medos.', 'O Resgate do Soldado Ryan', 4.2, 1998, 14, 169, 'Steven Spielberg', 'Matt Damon , Tom Hanks , Tom Sizemore , Vin Diesel , Adam Goldberg', 'Robert Rodat', 'Amblin Entertainment', 'resgate_soldado_ryan.jpg'),
(23, 'Carl Brashear (Cuba Gooding Jr.) veio de uma humilde família negra, que vivia em uma área rural em Sonora, Kentucky. Ainda garoto, no início dos anos 40, já adorava mergulhar, sendo que quando jovem se alistou na Marinha esperando se tornar um mergulhador. Inicialmente Carl trabalha como cozinheiro que era uma das poucas tarefas permitidas a um negro na época. Quando resolve mergulhar no mar em uma sexta-feira acaba sendo preso, pois os negros só podiam nadar na terça-feira, mas sua rapidez ao nadar é vista por todos e assim se torna um "nadador de resgate", por iniciativa do capitão Pullman (Powers Boothe). Quando Brashear solicita a escola de mergulhadores encontra o comandante Billy Sunday (Robert De Niro), um instrutor de mergulho áspero e tirânico que tem absoluto poder sobre suas decisões. No princípio Sunday faz muito pouco para encorajar as ambições de Brashear e o aspirante a mergulhador descobre que o racismo no exército é um fato quando os outros aspirantes brancos exceto Snowhill (Michael Rapaport), que por isto foi perseguido por Sunday se negam a compartilhar um alojamento com um negro. Mas a coragem e determinação de Brashear impressionam Sunday e os dois se tornam amigos quando Brashear tem de lutar contra o preconceito e a burocracia militar, que quer acabar com seus sonhos de se tornar comandante e reformá-lo.', 'Homens de Honra', 4.2, 2001, 12, 129, 'George Tillman Jr.', 'Cuba Gooding Jr. , Robert De Niro, Alimi Ballard, Allen Gerbino, Art Gotisar', 'Salvador Pérez Jr., Scott Marshall Smith', '', 'homens_de_honra.jpg'),
(24, 'Quando Hachiko, um filhote de cachorro da raça akita, é encontrado perdido em uma estação de trem por Parker (Richard Gere), ambos se identificam rapidamente. O filhote acaba conquistando todos na casa de Parker, mas é com ele que acaba criando um profundo laço de lealdade. Baseado em uma história real, Sempre ao seu Lado, é um emocionante filme sobre lealdade.', 'Sempre ao Seu Lado', 4.2, 2009, 0, 93, 'Lasse Hallstrom', 'Cary-Hiroyuki, Richard Gere, Bates Wilder, Davenia McFadden, Donna Sorbello', 'Kaneto Shindo, Stephen P. Lindsey', '', 'sempre_ao_seu_lado.jpg'),
(25, 'Gotham City, 1981. Em meio a uma onda de violência e a uma greve dos lixeiros que deixou a cidade imunda, o candidato Thomas Wayne (Brett Cullen) promete limpar a cidade na campanha para ser o novo prefeito. É neste cenário que Arthur Fleck (Joaquin Phoenix) trabalha como palhaço para uma agência de talentos, com um agente social o acompanhando de perto, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens de Wall Street em pleno metrô. A atitude inicia um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.', 'Coringa', 4.4, 2019, 16, 122, 'Todd Phillips', 'Joaquin Phoenix, Bill Camp, Brett Cullen, Brian Tyree, Bryan Callen', 'Bill Finger, Bob Kane, Jerry Robinson, Scott Silver, Todd Phillips', 'DC Films', 'coringa.jpg'),
(26, 'A história de otimismo ambientada no Mississippi em 1962, durante a gestação do movimento dos direitos civis nos EUA, acompanha Eugenia Phelan, jovem que acabou de se graduar e quer virar escritora, mas encontra a resistência da mãe, que quer vê-la casada. Aconselhada a escrever sobre o que a incomoda, Skeeter encontra um tema em duas mulheres negras: Aibileen, empregada que já ajudou a criar 17 crianças brancas mas chora a perda do próprio filho, e Minny, cozinheira de mão cheia que não arruma emprego porque não leva desaforo dos patrões para casa.', 'Histórias Cruzadas', 4.4, 2012, 12, 146, 'Tate Taylor', 'Allison Janney, Bryce Dallas, Emma Stone, Jessica Chastain, Octavia Spencer', 'Kathryn Stockett, Tate Taylor', 'DreamWorks SKG', 'historias_cruzadas.jpg'),
(27, 'Chris Gardner é um chefe e pai de família que enfrenta muitas dificuldades financeiras, vendendo aparelhos médicos que ninguém quer comprar por serem muito caros. Consegue uma vaga de estagiário numa importante corretora de ações, mas não recebe remuneração pelos serviços prestados, porém, persiste pois acredita que poderá ser futuramente contratado. A mulher o abandona e ele é obrigado a tomar conta sozinho do filho de apenas cinco anos de idade. Em meio a todas os problemas, eles são despejados do apartamento onde vivem por falta de pagamento, e têm de dormir em metrôs, banheiros públicos e asilos.', 'À Procura da Felicidade ', 4.2, 2006, 0, 117, 'Gabriele Muccino', 'Brian Howe, Dan Castellaneta, Doug Campbell, Jaden Smith, James Finnerty', 'Steven Conrad', 'Overbrook Entertainment', 'procura_da_felicidade.jpg'),
(28, 'Durante a Segunda Guerra Mundial, o médico do exército Desmond T. Doss se recusa a pegar em uma arma e matar pessoas, porém, durante a Batalha de Okinawa ele trabalha na ala médica e salva mais de 75 homens, sendo condecorado. O que faz de Doss o primeiro Opositor Consciente da história norte-americana a receber a Medalha de Honra do Congresso.', 'Até o Último Homem', 4.2, 2017, 16, 139, 'Mel Gibson', 'Andrew Garfield, Hugo Weaving, Luke Bracey, Sam Worthington, Teresa Palmer', 'Andrew Knight, Robert Schenkkan', 'Cross Creek Pictures', 'ate_o_ultimo_homem.jpg'),
(29, 'Auggie Pullman é um garoto que nasceu com uma deformação facial, o que fez com que passasse por 27 cirurgias plásticas. Aos 10 anos, ele pela primeira vez frequentará uma escola regular, como qualquer outra criança. Lá, precisa lidar com a sensação constante de ser sempre observado e avaliado por todos à sua volta.', 'Extraordinário', 4.3, 2017, 10, 113, 'Stephen Chbosky', 'Danielle Rose, Izabela Vidovic, Jacob Tremblay, Julia Roberts, Mandy Patinkin', 'Jack Thorne, R.J. Palacio, Stephen Chbosky, Steve Conrad', 'Lionsgate', 'extraordinario.jpg'),
(30, 'O solitário Andrew (Miles Teller) é um jovem baterista que sonha em ser o melhor de sua geração e marcar seu nome na música americana como fez Buddy Rich, seu maior ídolo na bateria. Após chamar a atenção do reverenciado e impiedoso mestre do jazz Terence Fletcher (J. K. Simmons), Andrew entra para a orquestra principal do conservatório de Shaffer, a melhor escola de música dos Estados Unidos. Entretanto, a convivência com o abusivo maestro fará Andrew transformar seu sonho em obsessão, fazendo de tudo para chegar a um novo nível como músico, mesmo que isso coloque em risco seus relacionamentos com sua namorada e sua saúde física e mental.', 'Whiplash: Em Busca da Perfeição', 4.4, 2014, 12, 106, 'Damien Chazelle', 'J. K. Simmons, Miles Teller, Paul Reiser, Adrian Burks, April Grace', 'Damien Chazelle', 'Sierra Affinity', 'whiplash.jpg'),
(31, 'Jack (Jacob Tremblay), um espirituoso menino de 5 anos, é cuidado por sua amada e devota Ma (Brie Larson). Como toda boa mãe, Ma se dedica em manter Jack feliz e seguro, cuidando dele com bondade e amor, e fazendo coisas típicas como brincar e contar histórias. Sua vida, entretanto, é tudo menos normal – eles estão presos – confinados em um espaço de 10 m² sem janelas, o qual Ma chamou eufemisticamente de “O Quarto de Jack”. Ma criou todo um universo para Jack dentro de O Quarto de Jack, e ela não parará por nada para garantir que, mesmo neste ambiente traiçoeiro, Jack seja capaz de viver uma vida completa e satisfatória. Mas, enquanto a curiosidade de Jack sobre a situação em que vivem cresce, e a resiliência de Ma alcança um ponto de ruptura, eles ensaiam um arriscado plano de escape, o que os leva a ficar face-a-face com o que pode ter se tornado a coisa mais assustadora: o mundo real.', 'O Quarto de Jack', 4.4, 2015, 14, 117, 'Lenny Abrahamson', 'Brie Larson, Jacob Tremblay, Joan Allen, Sean Bridgers, Amanda Brugel', 'Emma Donoghue', '', 'quarto_de_jack.jpg'),
(32, 'Uma Mente Brilhante é baseado no livro A Beautiful Mind: A Biography of John Forbes Nash Jr., de Sylvia Nasar. O filme conta a história real de John Nash que, aos 21 anos, formulou um teorema que provou sua genialidade. Brilhante, Nash chegou a ganhar o Prêmio Nobel. Diagnosticado como esquizofrênico pelos médicos, Nash enfrentou batalhas em sua vida pessoal, lutando até o fim de sua vida.', 'Uma Mente Brilhante ', 4.3, 2001, 12, 135, 'Ron Howard', 'Adam Goldberg, Alex Tanaka, Alex Toma, Amy Walz, Anthony Easton, Russel Crowe', 'Akiva Goldsman', 'Imagine Entertainment', 'uma_mente_brilhante.jpg'),
(33, 'Frank Abagnale Jr. (Leonardo DiCaprio) já foi médico, advogado e co-piloto, tudo isso com apenas 18 anos. Mestre na arte do disfarce, ele aproveita suas habilidades para viver a vida como quer e praticar golpes milionários, que fazem com que se torne o ladrão de banco mais bem-sucedido da história dos Estados Unidos com apenas 17 anos. Mas em seu encalço está o agente do FBI Carl Hanratty (Tom Hanks), que usa todos os meios que tem ao seu dispor para encontrá-lo e capturá-lo.', 'Prenda-me Se For Capaz', 4.2, 2002, 12, 141, 'Steven Spielberg', 'Christopher Walken, Leonardo DiCaprio, Martin Sheen, Nathalie Baye, Tom Hanks', 'Frank Abgnale Jr., Jeff Nathanson, Stan Redding', 'Amblin Entertainment', 'prenda_me_se_for_capaz.jpg'),
(34, 'A história é centrada em Katherine Johnson (Henson), uma brilhante matemática afroamericana que, ao lado das colegas Dorothy Vaughn e Mary Jackson, foi peça fundamental numa das maiores operações da história dos Estados Unidos: o lançamento do astronauta John Glenn para a órbita da Terra e seu retorno em segurança. Junto, o trio ultrapassou todos os limites de gênero, raça e profissionais para embarcar e serem muito bem-sucedidas nessa missão pioneira.', 'Estrelas Além do Tempo ', 4.3, 2016, 0, 127, 'Theodore Melfi', 'Janelle Monáe, Jim Parsons, Kevin Costner, Kirsten Dunst, Octavia Spencer', 'Alisson Schroeder, Margot Lee Shetterly', 'Fox 2000 Pictures', 'estrelas_alem_do_tempo.jpg'),
(35, 'Durante seis meses, Jordan Belfort (Leonardo DiCaprio) trabalhou duro em uma corretora de Wall Street, seguindo os ensinamentos de seu mentor Mark Hanna (Matthew McConaughey). Quando finalmente consegue ser contratado como corretor da firma, acontece o Black Monday, que faz com que as bolsas de vários países caiam repentinamente. Sem emprego e bastante ambicioso, ele acaba trabalhando para uma empresa de fundo de quintal que lida com papéis de baixo valor, que não estão na bolsa de valores. É lá que Belfort tem a ideia de montar uma empresa focada neste tipo de negócio, cujas vendas são de valores mais baixos mas, em compensação, o retorno para o corretor é bem mais vantajoso. Ao lado de Donnie (Jonah Hill) e outros amigos dos velhos tempos, ele cria a Stratton Oakmont, uma empresa que faz com que todos enriqueçam rapidamente e, também, levem uma vida dedicada ao prazer.', 'O Lobo de Wall Street', 4.1, 2013, 18, 180, 'Martin Scorsese', 'Leonardo DiCaprio, Margot Robbie, Matthew McConaughey, Rob Reiner, Aaron Glaser', 'Jordan Belfort, Terence Winter', 'Red Granite Pictures', 'lobo_wall_street.jpg'),
(36, 'Rico e bem sucedido, Will (Sam Claflin) leva uma vida repleta de conquistas, viagens e esportes radicais até ser atingido por uma moto, ao atravessar a rua em um dia chuvoso. O acidente o torna tetraplégico, obrigando-o a permanecer em uma cadeira de rodas. A situação o torna depressivo e extremamente cínico, para a preocupação de seus pais (Janet McTeer e Charles Dance). É neste contexto que Louisa Clark (Emilia Clarke) é contratada para cuidar de Will. De origem modesta, com dificuldades financeiras e sem grandes aspirações na vida, ela faz o possível para melhorar o estado de espírito de Will e, aos poucos, acaba se envolvendo com ele. Baseado no romance homônimo de Jojo Moyes.', 'Como Eu Era Antes de Você', 3.7, 2016, 12, 110, 'Thea Sharrock', 'Emilia Clarke, Sam Claflin, Amber Elizabeth, Ben Lloyd-Hughes, Brendan Coyle', 'Jojo Moyes', 'New Line Cinema', 'como_eu_era_antes_de_voce.jpg'),
(37, 'Thor encontra-se em uma jornada diferente de tudo que ele já enfrentou – uma busca pela paz interior, mas sua aposentadoria é interrompida por um assassino galáctico conhecido como Gorr, o Carniceiro dos Deuses, que busca a extinção dos deuses. Para combater a ameaça, Thor pede a ajuda do Rei Valquíria, Korg, e da ex-namorada Jane Foster que – para surpresa de Thor – inexplicavelmente empunha seu martelo mágico, Mjolnir, revelando-se a Poderosa Thor. Juntos, eles embarcam em uma angustiante aventura cósmica para descobrir o mistério da vingança do Carniceiro dos Deuses e detê-lo antes que seja tarde demais.', 'Thor: Amor e Trovão ', 3.2, 2022, 12, 119, 'Taika Waititi', 'Chris Hemsworth,Christian Bale Gorr, Natalie Portman,Tessa Thompson, Ben Falcone', 'Jennifer Kaytin Robinson, Stan LeeStan Lee, Taika WaititiTaika Waititi', 'Marvel Studios', 'thor.png'),
(38, 'Depois de sair do serviço ativo da MI6, James Bond vive tranquilamente na Jamaica, mas como nem tudo dura pouco, a vida do espião 007 é agitada mais uma vez. Felix Leiter é um velho amigo da CIA que procura o inglês para um pequeno favor de ajudá-lo em uma missão secreta. O que era pra ser apenas uma missão de resgate de um grupo de cientistas acaba sendo mais traiçoeira do que o esperado, levando o agente inglês 007 ao misterioso vilão, Safin, que utiliza de novas armas de tecnologia avançada e extremamente perigosa.', '007: Sem Tempo para Morrer', 3.6, 2021, 14, 163, 'Cary Fukunaga', 'Daniel Craig, Ana de Armas,Bem Whishaw, Billy Magnussen Logan, Christoph Waltz', 'Cary Fukunaga, Ian Fleming, Neal Purvis, Phoebe Waller-Bridge, Robert WadeRobert Wade', 'Metro-Goldwyn-Mayer', 'sem_tempo.jfif'),
(39, '“The Box” é um filme musical de jukebox sobre um aspirante a cantor e um produtor musical decadente que costumava ser um figurão na indústria. Juntos, eles embarcam em uma jornada musical.', 'The Box ', 3.4, 2021, 12, 94, 'Yang Jung Woong', 'ChanYeol, Jo Dal Hwan,Jung Hae-Kyun, Kim Ji Hyun', 'Yang Jung Woong', '', 'the_box.jfif'),
(40, 'Ataque dos Cães acompanha os irmãos Phil (Benedict Cumberbatch) e George (Jesse Plemons), que são ricos proprietários da maior fazenda de Montana. Enquanto o primeiro é brilhante, mas cruel, o segundo é a gentileza em pessoa. Quando George secretamente se casa com a viúva local Rose (Kirsten Dunst), o invejoso Phil faz tudo para atrapalhá-los.', 'Ataque dos cães', 3.7, 2021, 16, 127, 'Jane Campion', 'Benedict Cumberbatch, Kirsten Dunst, Kodi Smit-McPhee, Alice Englert, Frances Conroy', 'Don Winslow, Jane Campion, Nikolaj Arcel, Rasmus Heisterberg, Shane Salerno, Thomas Savage', 'New Zealand Film Commission, BBC Film', 'ataque_dos_caes.jfif'),
(41, 'Uma garota chamada Mirabel Madrigal cresce como o único membro não mágico de sua família, que vivem escondidos em uma vibrante casa encantada nas montanhas da Colômbia.', 'Encanto', 3.8, 2021, 0, 109, 'Byron Howard, Charise Castro, Smith Jared Bush', 'Stephanie Beatriz, Adassa Martins, Angie Cepeda, Carolina Gaitán, Diane Guerrero', 'Charise Castro Smith, Jared Bush, Lin-Manuel Miranda', 'Walt Disney', 'encanto.jfif'),
(42, 'A porta do multiverso, cheia de mistério e loucura, se abre. Agora que o Homem de Ferro e o Capitão América partiram após uma batalha feroz contra Thanos, o ex-cirurgião genial, e mago mais forte de todos, Doutor Estranho, deve desempenhar um papel ativo como uma figura central nos Vingadores. No entanto, usar sua magia para manipular o tempo e o espaço à vontade com um feitiço proibido, que é considerado o mais perigoso, abriu as portas para uma misteriosa loucura chamada “o Multiverso”. Para restaurar um mundo onde tudo está mudando, Strange busca a ajuda de seu aliado Wong, o Mago Supremo, e da Feiticeira Escarlate, a Vingadora mais poderosa, Wanda. Mas uma terrível ameaça paira sobre a humanidade e todo o universo, que não pode mais ser detida apenas com seu poder. O que ainda mais surpreendente, é que a maior ameaça do universo se parece exatamente com o Doutor Estranho…', 'Doutor Estranho no Multiverso da Loucura', 3.6, 2022, 14, 126, 'Sam Raimi', 'Benedict Cumberbatch, Benedict Wong, Elizabeth Olsen, Rachel McAdams, Xochitl Gomez', 'Michael Waldron, Stan LeeStan, DitkoSteve Ditk', 'Marvel Studios', 'dr_estranho.png')
;

INSERT INTO categorias (id_categoria, nome_categoria)
values (1, 'Animação'),
(2, 'Aventura'),
(3, 'Comédia'),
(4, 'Família'),
(5, 'Fantasia'),
(6, 'Mistério'),
(7, 'Policial'),
(8, 'Musical'),
(9, 'Drama'),
(10, 'Romance'),
(11, 'Guerra'),
(12, 'Ação'),
(13, 'Biografia'),
(14, 'Super-Herói'),
(15, 'Suspense'),
(16, 'História'),
(17, 'Música'),
(18, 'Lançamento'),
(19, 'Oscar'),
(20, 'Faroeste')
;

INSERT INTO filme_categoria(id_filme_categoria, id_filme, id_categoria)
values (DEFAULT, 1, 1),
(DEFAULT, 2, 1),
(DEFAULT, 3, 1),
(DEFAULT, 4, 1),
(DEFAULT, 5, 1),
(DEFAULT, 6, 1),
(DEFAULT, 7, 1),
(DEFAULT, 8, 1),
(DEFAULT, 9, 1),
(DEFAULT, 10, 1),
(DEFAULT, 11, 1),
(DEFAULT, 12, 1),
(DEFAULT, 13, 1),
(DEFAULT, 14, 1),
(DEFAULT, 15, 1),
(DEFAULT, 16, 1),
(DEFAULT, 17, 1),
(DEFAULT, 18, 1),
(DEFAULT, 1, 2),
(DEFAULT, 2, 2),
(DEFAULT, 3, 2),
(DEFAULT, 4, 2),
(DEFAULT, 5, 2),
(DEFAULT, 6, 2),
(DEFAULT, 7, 2),
(DEFAULT, 8, 2),
(DEFAULT, 9, 2),
(DEFAULT, 10, 2),
(DEFAULT, 11, 2),
(DEFAULT, 12, 2),
(DEFAULT, 13, 4),
(DEFAULT, 14, 2),
(DEFAULT, 15, 3),
(DEFAULT, 16, 2),
(DEFAULT, 17, 2),
(DEFAULT, 18, 2),
(DEFAULT, 2, 3),
(DEFAULT, 3, 3),
(DEFAULT, 4, 3),
(DEFAULT, 5, 3),
(DEFAULT, 6, 3),
(DEFAULT, 7, 3),
(DEFAULT, 8, 3),
(DEFAULT, 9, 3),
(DEFAULT, 10, 9),
(DEFAULT, 11, 3),
(DEFAULT, 12, 3),
(DEFAULT, 13, 5),
(DEFAULT, 14, 3),
(DEFAULT, 15, 4),
(DEFAULT, 16, 3),
(DEFAULT, 17, 3),
(DEFAULT, 18, 5),
(DEFAULT, 2, 4),
(DEFAULT, 3, 4),
(DEFAULT, 4, 4),
(DEFAULT, 5, 9),
(DEFAULT, 6, 4),
(DEFAULT, 7, 9),
(DEFAULT, 8, 4),
(DEFAULT, 10, 4),
(DEFAULT, 11, 4),
(DEFAULT, 12, 4),
(DEFAULT, 13, 8),
(DEFAULT, 14, 4),
(DEFAULT, 16, 4),
(DEFAULT, 3, 5),
(DEFAULT, 4, 6),
(DEFAULT, 5, 4),
(DEFAULT, 6, 5),
(DEFAULT, 7, 4),
(DEFAULT, 8, 5),
(DEFAULT, 10, 8),
(DEFAULT, 12, 5),
(DEFAULT, 13, 10),
(DEFAULT, 14, 5),
(DEFAULT, 16, 5),
(DEFAULT, 4, 7),
(DEFAULT, 5, 5),
(DEFAULT, 6, 8),
(DEFAULT, 14, 8),
(DEFAULT, 19, 9),
(DEFAULT, 19, 10),
(DEFAULT, 20, 9),
(DEFAULT, 20, 3),
(DEFAULT, 20, 11),
(DEFAULT, 20, 10),
(DEFAULT, 21, 9),
(DEFAULT, 22, 9),
(DEFAULT, 22, 12),
(DEFAULT, 22, 11),
(DEFAULT, 23, 9),
(DEFAULT, 23, 13),
(DEFAULT, 24, 9),
(DEFAULT, 24, 4),
(DEFAULT, 25, 9),
(DEFAULT, 25, 7),
(DEFAULT, 25, 14),
(DEFAULT, 25, 15),
(DEFAULT, 26, 9),
(DEFAULT, 27, 9),
(DEFAULT, 27, 13),
(DEFAULT, 28, 9),
(DEFAULT, 28, 11),
(DEFAULT, 28, 16),
(DEFAULT, 29, 9),
(DEFAULT, 29, 4),
(DEFAULT, 30, 9),
(DEFAULT, 30, 17),
(DEFAULT, 31, 9),
(DEFAULT, 32, 9),
(DEFAULT, 32, 13),
(DEFAULT, 33, 9),
(DEFAULT, 33, 13),
(DEFAULT, 33, 7),
(DEFAULT, 34, 9),
(DEFAULT, 34, 13),
(DEFAULT, 34, 16),
(DEFAULT, 35, 9),
(DEFAULT, 35, 13),
(DEFAULT, 35, 7),
(DEFAULT, 36, 9),
(DEFAULT, 36, 10),
(DEFAULT, 37, 12),
(DEFAULT, 37, 2),
(DEFAULT, 37, 14),
(DEFAULT, 37, 18),
(DEFAULT, 38, 12),
(DEFAULT, 38, 19),
(DEFAULT, 39, 9),
(DEFAULT, 39, 8),
(DEFAULT, 39, 19),
(DEFAULT, 40, 9),
(DEFAULT, 40, 20),
(DEFAULT, 40, 6),
(DEFAULT, 40, 19),
(DEFAULT, 41, 1),
(DEFAULT, 41, 4),
(DEFAULT, 41, 5),
(DEFAULT, 41, 19),
(DEFAULT, 42, 14),
(DEFAULT, 42, 12),
(DEFAULT, 42, 2),
(DEFAULT, 42, 18)
;

SELECT * FROM FILMES;
SELECT * FROM CATEGORIAS;
SELECT * FROM FILME_CATEGORIA;

